import type { TFunction } from 'i18next'
import type { ChatMessage } from './types'

export function createInitialMessages(t: TFunction): ChatMessage[] {
  return [
    {
      id: 'text-incoming',
      type: 'text',
      direction: 'incoming',
      sentAt: '09:41',
      text: t('chat.intro'),
      reactions: [{ emoji: '👍', count: 2 }, { emoji: '💙' }],
    },
    {
      id: 'text-undelivered',
      type: 'text',
      direction: 'outgoing',
      sentAt: '09:42',
      status: 'undelivered',
      text: t('chat.reply'),
    },
    {
      id: 'image',
      type: 'image',
      direction: 'outgoing',
      sentAt: '09:43',
      status: 'delivered',
      url: 'https://placehold.co/720x420/0866ff/ffffff?text=Campaign+preview',
      alt: t('chat.imageAlt'),
      caption: t('chat.imageCaption'),
      reactions: [{ emoji: '🔥', count: 3 }],
    },
    {
      id: 'video',
      type: 'video',
      direction: 'outgoing',
      sentAt: '09:44',
      status: 'read',
      url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
      caption: t('chat.videoCaption'),
    },
    {
      id: 'document',
      type: 'document',
      direction: 'incoming',
      sentAt: '09:46',
      fileName: 'Q3-campaign-results.pdf',
      mimeType: 'application/pdf',
      size: '2.4 MB',
      caption: t('chat.documentCaption'),
    },
    {
      id: 'voice',
      type: 'voice',
      direction: 'incoming',
      sentAt: '09:48',
      duration: '0:18',
      progress: 34,
      waveform: [
        28, 52, 38, 74, 44, 82, 64, 34, 56, 90, 46, 68, 40, 78, 58, 32, 62, 48,
        72, 36, 54, 30,
      ],
      reactions: [{ emoji: '😂' }],
    },
    {
      id: 'audio',
      type: 'audio',
      direction: 'outgoing',
      sentAt: '09:50',
      status: 'read',
      title: 'Brand theme.mp3',
      artist: 'MBA Studio',
      duration: '3:24',
    },
    {
      id: 'location',
      type: 'location',
      direction: 'incoming',
      sentAt: '09:52',
      latitude: -23.5614,
      longitude: -46.6559,
      name: t('chat.locationName'),
      address: t('chat.locationAddress'),
    },
    {
      id: 'contact',
      type: 'contact',
      direction: 'incoming',
      sentAt: '09:54',
      contacts: [
        {
          formattedName: 'Maya Chen',
          givenName: 'Maya',
          familyName: 'Chen',
          organization: 'MBA Studio',
          title: t('chat.contactRole'),
          birthday: '1992-04-18',
          phones: [{ label: 'CELL', value: '+55 11 99999-2048' }],
          emails: [{ label: 'WORK', value: 'maya@example.com' }],
          addresses: [
            {
              label: 'WORK',
              street: 'Av. Paulista, 1578',
              city: 'São Paulo',
              region: 'SP',
              postalCode: '01310-200',
              country: 'Brazil',
            },
          ],
          urls: [{ label: 'WORK', value: 'https://example.com' }],
        },
      ],
    },
    {
      id: 'location-request',
      type: 'location-request',
      direction: 'outgoing',
      sentAt: '09:56',
      status: 'delivered',
      prompt: t('chat.locationPrompt'),
      buttonLabel: t('chat.sendLocation'),
    },
    {
      id: 'sticker',
      type: 'sticker',
      direction: 'incoming',
      sentAt: '09:57',
      url: 'https://placehold.co/240x240/7c3aed/ffffff?text=%E2%9C%A8',
      alt: t('chat.stickerAlt'),
    },
    {
      id: 'button-one',
      type: 'buttons',
      direction: 'outgoing',
      sentAt: '10:00',
      status: 'read',
      text: t('chat.appointment'),
      footer: 'MBA Support',
      buttons: [{ id: 'confirm', title: t('chat.confirmAppointment') }],
    },
    {
      id: 'button-two',
      type: 'buttons',
      direction: 'outgoing',
      sentAt: '10:01',
      status: 'read',
      text: t('chat.continuePrompt'),
      buttons: [
        { id: 'yes', title: t('chat.yes') },
        { id: 'no', title: t('chat.notNow') },
      ],
    },
    {
      id: 'button-three',
      type: 'buttons',
      direction: 'outgoing',
      sentAt: '10:02',
      status: 'delivered',
      text: t('chat.orderHelp'),
      buttons: [
        { id: 'track', title: t('chat.trackOrder') },
        { id: 'change', title: t('chat.changeDelivery') },
        { id: 'support', title: t('chat.talkSupport') },
      ],
    },
    {
      id: 'list',
      type: 'list',
      direction: 'outgoing',
      sentAt: '10:04',
      status: 'read',
      title: t('chat.chooseService'),
      text: t('chat.chooseServiceText'),
      buttonLabel: t('chat.viewServices'),
      sections: [
        {
          title: t('chat.popular'),
          rows: [
            {
              id: 'sales',
              title: t('chat.sales'),
              description: t('chat.salesDescription'),
            },
            {
              id: 'support',
              title: t('chat.customerSupport'),
              description: t('chat.supportDescription'),
            },
          ],
        },
        {
          title: t('chat.account'),
          rows: [
            {
              id: 'billing',
              title: t('chat.billing'),
              description: t('chat.billingDescription'),
            },
            {
              id: 'profile',
              title: t('chat.profile'),
              description: t('chat.profileDescription'),
            },
          ],
        },
      ],
    },
    {
      id: 'url',
      type: 'url-button',
      direction: 'outgoing',
      sentAt: '10:06',
      status: 'read',
      text: t('chat.reportLinkText'),
      label: t('chat.openReport'),
      url: 'https://example.com/reports/q3',
    },
    {
      id: 'carousel',
      type: 'carousel',
      direction: 'outgoing',
      sentAt: '10:08',
      status: 'delivered',
      reactions: [{ emoji: '❤️', count: 2 }],
      items: [
        {
          id: 'starter',
          imageUrl: 'https://placehold.co/640x360/0866ff/ffffff?text=Starter',
          imageAlt: t('chat.plans.starter'),
          title: t('chat.plans.starter'),
          description: t('chat.plans.starterDescription'),
          button: { id: 'starter', title: t('chat.plans.chooseStarter') },
        },
        {
          id: 'growth',
          imageUrl: 'https://placehold.co/640x360/7c3aed/ffffff?text=Growth',
          imageAlt: t('chat.plans.growth'),
          title: t('chat.plans.growth'),
          description: t('chat.plans.growthDescription'),
          button: { id: 'growth', title: t('chat.plans.chooseGrowth') },
        },
        {
          id: 'scale',
          imageUrl: 'https://placehold.co/640x360/0f766e/ffffff?text=Scale',
          imageAlt: t('chat.plans.scale'),
          title: t('chat.plans.scale'),
          description: t('chat.plans.scaleDescription'),
          button: { id: 'scale', title: t('chat.plans.contactSales') },
        },
      ],
    },
  ]
}
