info:
  name: Set or update commerce settings
  type: http
  seq: 2

http:
  method: POST
  url: https://graph.facebook.com/{{Version}}/{{Phone-Number-ID}}/whatsapp_commerce_settings?is_cart_enabled=true&is_catalog_visible=true
  params:
    - name: is_cart_enabled
      value: "true"
      type: query
    - name: is_catalog_visible
      value: "true"
      type: query
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false

examples:
  - name: Example response
    request:
      url: https://graph.facebook.com/{{Version}}/{{Phone-Number-ID}}/whatsapp_commerce_settings?is_cart_enabled=false&is_catalog_visible=false
      method: POST
      params:
        - name: is_cart_enabled
          value: "false"
          type: query
        - name: is_catalog_visible
          value: "false"
          type: query
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json; charset=UTF-8
        - name: Vary
          value: Origin
        - name: cross-origin-resource-policy
          value: cross-origin
        - name: x-app-usage
          value: '{"call_count":0,"total_cputime":0,"total_time":0}'
        - name: x-fb-rlafr
          value: "0"
        - name: Access-Control-Allow-Origin
          value: "*"
        - name: facebook-api-version
          value: v16.0
        - name: Strict-Transport-Security
          value: max-age=15552000; preload
        - name: Pragma
          value: no-cache
        - name: Cache-Control
          value: private, no-cache, no-store, must-revalidate
        - name: Expires
          value: Sat, 01 Jan 2000 00:00:00 GMT
        - name: x-fb-request-id
          value: AB0EvD-U5WkosUqnPBMwXhB
        - name: x-fb-trace-id
          value: A5pEgwxfemZ
        - name: x-fb-rev
          value: "1007268877"
        - name: X-FB-Debug
          value: 03bVIwTYJnh6qJe3sqWWNGapvvRoU/yKE+3nC45djcuaeV41y+6Z4SgWhK/SRB+WUUBEKWInR4hxFzHnKZ1+7Q==
        - name: Date
          value: Fri, 07 Apr 2023 20:01:14 GMT
        - name: Alt-Svc
          value: h3=":443"; ma=86400
        - name: Connection
          value: keep-alive
        - name: Content-Length
          value: "16"
      body:
        type: json
        data: |-
          {
              "success": true
          }

docs: |-
  - Guide: [Sell Products & Services](https://developers.facebook.com/docs/whatsapp/cloud-api/guides/sell-products-and-services) (Cloud API)
  - Guide: [Sell Products & Services](https://developers.facebook.com/docs/whatsapp/on-premises/guides/commerce-guides) (On-Premises API)
  - Endpoint reference: [WhatsApp Business Phone Number > WhatsApp Commerce Settings](https://developers.facebook.com/docs/graph-api/reference/whats-app-business-account-to-number-current-status/whatsapp_commerce_settings)
