import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const audience = process.env.DOCUSAURUS_AUDIENCE ?? 'external'
const isInternal = audience === 'internal'

if (!isInternal && audience !== 'external') {
  throw new Error(
    `Invalid DOCUSAURUS_AUDIENCE "${audience}". Expected "external" or "internal".`,
  )
}

const sidebars: SidebarsConfig = {
  documentationSidebar: [
    isInternal ? 'internal' : 'home',
    {
      type: 'category',
      label: 'Features',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Workspace',
          items: [
            'features/workspace/home-and-performance-overview',
            'features/workspace/queue-and-team-coordination',
            'features/workspace/whatsapp-inbox',
            'features/workspace/human-and-ai-handoff',
            'features/workspace/contacts',
            'features/workspace/groups',
            'features/workspace/template-management',
            'features/workspace/template-sending',
            'features/workspace/organization-management',
            'features/workspace/channel-administration',
            'features/workspace/user-administration',
          ],
        },
        ...(isInternal
          ? [
              {
                type: 'category' as const,
                label: 'Management',
                items: [
                  'features/management/home-and-performance-overview.internal',
                  'features/management/agent-lifecycle-management.internal',
                  'features/management/agent-skills-and-knowledge.internal',
                  'features/management/agent-evaluations.internal',
                  'features/management/backups-export-and-import.internal',
                  'features/management/agent-studio.internal',
                  'features/management/webhook-visibility.internal',
                  'features/management/functions-and-mcp-packages.internal',
                  'features/management/api-keys-and-access-control.internal',
                  'features/management/api-playgrounds.internal',
                  'features/management/organization-and-application-administration.internal',
                ],
              },
            ]
          : []),
      ],
    },
    {
      type: 'category',
      label: 'Archive',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'archive' }],
    },
  ],
}

export default sidebars
